### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by arjunguha** [cakeplus/mparser#1]
Hi all,

I'd love to see a release that doesn't require PCRE. Is there anything I can do to help? I'd be happy to figure out how to merge the two branches, or anything else.

**Comment by cakeplus** [comment]
Hi, Arjun!

Sorry again for the unresponsiveness.

Everything is ready for the release except that we need the library author's blessing (@harnold). I've sent him a message and wait for his decision. Can't make a release without it, as I only maintain the package, not the library. Perhaps he will overtake the repository, since it's on GitHub now.

**Comment by jcollard** [comment]
Thanks. Any updates on this? I would also be happy to help.

**Comment by cakeplus** [comment]
1.1 [is out](https://github.com/cakeplus/mparser/releases) and [should soon](https://github.com/cakeplus/mparser/releases) appear in OPAM. I've contacted @harnold, and we decided that I continue maintaining not only the package but also the library, since Holger is a very busy man (none other than a traveling programmer!).

Enjoy the release!
