### ISSUE TITLE
add a non_space parser

### ISSUE THREAD

**Issue by martindemello** [cakeplus/mparser#7]
i found myself defining this a couple of times; it's probably worth having as a standard char parser, especially if i've made some subtle mistake :)

````
let non_space : (char, unit) parser = none_of " \t\r\n"
````

**Comment by cakeplus** [comment]
A good suggestion! Perhaps it would be better to add a `not` combinator?
```
val not: (char, 's) t -> (char, 's) t
```

You could then use `not space` instead of `non_space`.

**Comment by martindemello** [comment]
yeah, that would be even better. (i actually went and looked for a `not` combinator in the docs when i was trying to implement `non_space`, then forgot about doing it that way)

**Comment by cakeplus** [comment]
Since `not` is a standard OCaml builtin, I chose to name the new function [is_not](https://github.com/cakeplus/mparser/commit/c45f52a4b6dd561bbe1958f35a6638854f5a977d). I've added [non_space](https://github.com/cakeplus/mparser/commit/14c32f3589124979ede78b33dd6eeb39e91d9a31) as well, for better messages and performance.

A [minor release](https://github.com/cakeplus/mparser/releases/tag/1.2.3) should hit OPAM soon.

(insider leak: a major release is in the works)
